{% set version = "0.2.0" %}

package:
  name: tophu
  version: {{ version }}

source:
  url: https://github.com/isce-framework/tophu/archive/v{{ version }}.tar.gz
  sha256: f1185ffc5f5cfbb7fb85ee7f5b0c42d2ba96824b2ec148926b6662b2036f3683

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools >=42
  run:
    - __linux  # [linux]
    - dask >=2022.05.1
    - h5py >=3
    - isce3 >=0.12
    - numpy >=1.21
    - python >=3.8
    - rasterio >=1.3
    - scipy >=1.5

test:
  imports:
    - tophu
  requires:
    - pytest >=6
    - pytest-cov
  source_files:
    - test
  commands:
    - pytest

about:
  home: https://github.com/isce-framework/tophu
  summary: Multi-scale 2-D phase unwrapping
  license: BSD-3-Clause OR Apache-2.0
  license_file:
    - LICENSE-Apache-2.0
    - LICENSE-BSD-3-Clause
  doc_url: https://tophu.readthedocs.io
  dev_url: https://github.com/isce-framework/tophu

extra:
  recipe-maintainers:
    - gmgunter
